### ISSUE TITLE
Missing some file

### ISSUE THREAD

**Issue by sxmayd** [uoe-agents/PO-GPL#2]
Dear Authors,

Excuse the liberty I may take to write you this issue.

When I run the code, I find that maybe it lacks of the file named "test_gpl_demo.py", which cause the code list as follows get error

for j in `seq 1 $exp`
do
    for i in `seq 0 $max`
    do
    echo " "
    echo "GPL-Q LBF"
    echo "seed number" $j "checkpoint number" $i
    python test_gpl_demo.py --lr=0.00025 --env-name='PO-Adhoc-Foraging-2-12x12-3f-v0' \
      --google-cloud="False" --designated-cuda="cuda:0" \
      --seed=6 --eval-init-seed=65 --eval-seed=5 --load-from-checkpoint=$i \
      --q-loss-weight=1.0 --act-reconstruction-weight=0.05 --lrf-rank=6  \
      --exp-name="GPL/exp_$j" --logging-dir="test_lbf_log" --saving-dir="test_lbf" 
    done
done

**Comment by IgnacioCarlucho** [comment]
Hi sxmayd, 

Thanks for pointing this out. I added the missing file. 

You should be able to run the analysis now. 

Please let me know if there is anything else you need help with. 

Ignacio
